markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

title: Paho Blog

description: "A blog by Paho."
url: http://paholg.com
baseurl: /

author:
  name: "Paho Lurie-Gregg"
  email: paho@paholg.com

sass:
  style: compressed

github:
  repo: "https://github.com/paholg/"

projects:
  - { title: Dimensioned, url: "https://github.com/paholg/dimensioned/" }
  - { title: Typenum, url: "https://github.com/paholg/typenum/" }

recipes:
  url: "/recipes"
