# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Paho Blog

description:      "A blog about some projects I've been working on."
url:              http://paholg.com
baseurl:          /

author:
  name:           "Paho Lurie-Gregg"
  email:          paho@paholg.com

paginate:         5

github:
  repo:           "https://github.com/paholg/"

collections:
  dimensioned:
    output: true
    title: Dimensioned
    url: /dimensioned
    background: "/imgs/bg-dimensioned.jpg"
    links:
      Documentation: /doc/dimensioned
      Source: "https://github.com/paholg/dimensioned"
    crates:
      img: https://img.shields.io/crates/v/dimensioned.svg
      url: https://crates.io/crates/dimensioned

  # recipes:
  #   output: true
  #   title: Recipes
  #   url: /recipes
  #   links:
  #     Source: "https://github.com/paholg/recipes"
